name: Deploy ETL Pipeline

on:
  pull:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install AWS CLI
      run: |
        pip install awscli
        aws --version

    - name: Run Deployment Script
      run: |
        chmod +x deploy-ci.sh
        ./deploy-ci.sh